Un-blur update popup for chromium browsers
Magic-Fishes/Ecole-Directe-Plus pull request #36
Opened 2024-08-14 07:50 UTC by OeildeLynx31

Just see [before](https://github.com/user-attachments/assets/3dfefafd-617c-4da9-8f95-ded01299404f) and [after](https://github.com/user-attachments/assets/978cdb9b-6300-4f31-bd1b-816916b52f92).

2024-08-14 08:39 UTC, OeildeLynx31 commented
✅ Ready to merge

2024-08-14 17:24 UTC, OeildeLynx31 commented
I have found some contrast issues, I don't know if I should fix them or not:
- Light theme, change theme button:
![image](https://github.com/user-attachments/assets/5c7646cc-2bb4-41e8-b77b-dbd30aafb44d)

- Dark theme, "Communauté" tab:
![image](https://github.com/user-attachments/assets/ea6b12bb-20b9-422f-8cfb-56688af99db0)
The white on dark-blue should be less contrasted (It's my personnal feeling)

2024-08-14 17:28 UTC, OeildeLynx31 commented
I also noticed that the screenshots are not in a good quality (little image size, jpeg image format used)

2024-08-15 04:07 UTC, Truiteseche requested changes
Bug well found and solution well implemented! However I think we should keep the `overflow-y: auto` as it is today.

2024-08-15 04:07 UTC, Truiteseche commented on src/components/generic/PopUps/PopUp.css
> +    /* overflow-y: auto; */
We should keep that enabled, it's useful in extreme responsive situation and has no drawbacks otherwise.

2024-08-15 09:04 UTC, OeildeLynx31 commented on src/components/generic/PopUps/PopUp.css
> +    /* overflow-y: auto; */
This is bluring the entire popup, and for the "extreme responsive situation" we could use `@media screen` instead.

2024-08-15 20:03 UTC, Truiteseche commented on src/components/generic/PopUps/PopUp.css
> +    /* overflow-y: auto; */
Otherwise I think it's ready to merge 👍

2024-08-15 20:10 UTC, merged