Added long press to fetch calendar mobile, fixed progress bar calenda…
Magic-Fishes/Ecole-Directe-Plus pull request #44
Opened 2024-09-27 21:34 UTC by Fefedu973

…r fetch styling issue chrome, updated calendar tooltip, fixed landing page horizontal scrolling bug mobile

2024-09-29 14:37 UTC, Truiteseche commented
Is it ready to be reviewed and merged or is it still a draft @Fefedu973 ?

2024-09-29 14:38 UTC, Fefedu973 commented
It depends of what needs to be added, is the long press on mobile already here ? Don't merge the landing page btw

2024-10-04 20:22 UTC, Fefedu973 commented
@Truiteseche c'est prêt à merge

2024-10-20 22:10 UTC, Fefedu973 commented
To solve the conflictt you should keep my version (i have implemented the get all fix in the request) btw i think the size of the pr should now be updated from XL to XXXL

2024-11-10 00:48 UTC, Truiteseche requested changes

2024-11-10 00:48 UTC, Truiteseche commented on src/components/app/Account/Account.jsx
> +
Some accounts do not have access to these settings, resulting in the TypeError error `TypeError: accountsList[activeAccount] is undefined`

This is blocking me so I can't review the new documents section further.

2024-11-10 00:48 UTC, Truiteseche commented on src/components/app/Account/Account.jsx
> +                                        {module.params.DocumentsFactureActif === "1" && documents?.factures?.length > 0 && (
Here it should work for me but maybe some accounts don't have those params as well. It may be relevant to handle the edge case where it's undefined

2024-11-10 00:48 UTC, Truiteseche commented on src/components/app/Account/Account.css
> +    var(--font-size-20);
Probably involuntary, I think there should be a `color` attribute here

2024-11-10 00:48 UTC, Truiteseche commented on src/components/app/Account/Account.css
> +    overflow: scroll;
Actually you probably want it to be `auto`, because `scroll` will always display a scrollbar even if it's empty, when `auto` will display only when the content overflows

2024-11-11 14:31 UTC, merged

2024-11-11 14:31 UTC, Truiteseche commented
Perfectly done. Thanks a lot 💯